introduce gh-action-runner deployment
kubev2v/forkliftci pull request #92
Opened 2023-05-22 07:11 UTC by eslutsky

deploy gh-action runner VM on ovirt

2023-05-22 12:52 UTC, mnecas requested changes

2023-05-22 12:52 UTC, mnecas commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +          msg: "{{ result  }}"
Remove extra space after `result`

2023-05-22 12:52 UTC, mnecas commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +          dnf: name="@Development tools" state=present
Please split the string to dict items

2023-05-22 12:52 UTC, mnecas commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +            curl -L https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz -o /tmp/k9s.tar.gz
Hmm would probably also move this to some variable so we don't need to go through code to know which version do we install

2023-05-22 12:52 UTC, mnecas commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +      - name: upgrade to fedora-36
Why do we need to upgrade to fedora 36?
What is the base OS version and why can't we install the 36 originally?

2023-06-12 11:30 UTC, eslutsky commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +              mac_address: "{{test_vm_mac_address | default(omit)}}"
its not set , so its  omitted in our case, 
but its useful when deploying on environment  where we want to control the IP address (throughout a pre-define mac-address reservation)

2023-06-12 11:32 UTC, eslutsky commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +      - ansible.posix
yea its become pretty long .  but i think we do this in different refactor PR.

2023-06-13 07:03 UTC, ahadas approved these changes

2023-06-13 07:06 UTC, ahadas commented on cluster/gh-action-runner/gh-action-runner-template-create.yml
> +      - ansible.posix
> but i think we do this in different refactor PR.

ack

2023-06-13 07:08 UTC, merged